/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-06-09 01:09:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang='pt-BR'>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Minha pÃ¡gina</title>\r\n");
      out.write("\t\t<meta charset = 'utf-8'>\r\n");
      out.write("\t\t<link rel=\"icon\" href=\"icone.png\" type=\"image/png\" />\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"image.png\" type=\"image/png\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t\t<meta name=\"google-site-verification\" content=\"CFRU3GMSVPownkObtOn5ZXQgMvG9pDXRyOME0DqvXx4\" />\r\n");
      out.write("\t\t<script src=\"codigo.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body onload=\"finishLoad()\" onpageshow=\"pageShow()\">\r\n");
      out.write("\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<form method=\"POST\" action=\"Login\" class=\"login\">\r\n");
      out.write("\t\t\t\t<label></label><input type=\"text\" name=\"usuario\" id=\"login\" placeholder=\"Login\"><br><br>\r\n");
      out.write("\t\t\t\t<label></label><input type=\"password\" name=\"senha\" id=\"senha\" placeholder=\"Senha\"><br><br>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"entrar\" id=\"entrar\" name=\"entrar\"><br>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t<img src=\"logo2.png\" width=\"380px\" height=\"160px\" title=\"My page\" alt=\"Image failed\"></img>\r\n");
      out.write("\t\t\t<form class=\"pesquisa\" action=\" \" method=\"post\" title=\"Buscar\">\r\n");
      out.write("  \t\t\t<label for=\"busca\"></label>\r\n");
      out.write("  \t\t\t\t<input type=\"search\" id=\"busca\" name=\"q\" placeholder=\"Buscar\">\r\n");
      out.write("  \t\t\t\t<button type=\"submit\">OK</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<lr>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o um</ld>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o dois</ld>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o trÃªs</ld>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o quatro</ld>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o cinco</ld>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o seis</ld>\r\n");
      out.write("\t\t\t\t<ld class=\"button\" title=\"BotÃ£o\">BotÃ£o sete</ld>\r\n");
      out.write("\t\t\t</lr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"secao\" >\r\n");
      out.write("\t\t\t<br>Coisas\r\n");
      out.write("\t\t<a href=\"http://www.google.com\" target=\"_blank\">Google</a>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\tCaio CÃ©sar, 2019.\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
